Week 2
produtoreativo/adora-front pull request #8
Opened 2022-09-17 21:09 UTC by diogochaves

O projeto já estava com o workflow ajustado para os testes com coverage, snyk, sonar. Teve modificações apenas dos parâmetros de configuração para testar as ferramentas.

Alterações:
- Criação de Secrets para os parâmetros do Sonar e S3/Cloudfront, assim não é preciso alterar os arquivos para testes de deploy do fork.
- Badges no Readme para o Sonar e Snyk (apontando para as contas produtoreativo)

2022-09-17 21:13 UTC, diogochaves commented
Não sei se as alterações são válidas, já que acrescenta mais Secrets ao projeto (e é quase que só "perfumaria").

2022-10-01 13:49 UTC, cmilfont approved these changes

2022-10-01 13:49 UTC, cmilfont requested changes
resolver conflitos

2022-10-03 22:42 UTC, diogochaves commented
configuração de deploy alterada

2022-10-05 17:58 UTC, cmilfont approved these changes

2022-10-05 17:58 UTC, merged