Sentry config
produtoreativo/adora-front pull request #9
Opened 2022-09-20 14:31 UTC by crgmzlps

Foi adicionado a configuração do Sentry com GH Actions para novos deploy

2022-10-01 13:51 UTC, cmilfont approved these changes

2022-10-01 13:51 UTC, cmilfont requested changes
resolver os conflitos

2022-10-01 14:23 UTC, crgmzlps commented
Configuração alterada.

2022-10-05 19:41 UTC, crgmzlps commented
conflitos resolvido

2022-10-07 11:50 UTC, merged